[package]
name = "androidsimulator-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "androidsimulator_core"
crate-type = ["rlib", "cdylib"]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
] }
